mtafiti/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from mtafiti import views

urlpatterns = [
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout'),
    url(r'^', include('publications.urls')),
    url(r'^admin/', admin.site.urls),
]

publications/urls.py
from django.conf.urls import url
from publications import views

app_name = 'publications'
urlpatterns = [
    url(r'^author-autocomplete/$', views.AuthorAutocomplete.as_view(create_field='name'), name='author-autocomplete'),
    url(r'^$', views.publication_listing, name='publication-listing'),
    url(r'^publication/add/$', views.manage_publication, name='add-publication'),
    url(r'^publication/(?P<pk>[0-9]+)/$', views.publication_details, name='publication-details'),
    url(r'^publication/(?P<pk>[0-9]+)/edit/$', views.manage_publication, name='edit-publication'),
    url(r'^publication/confirm-publication-details/$', views.confirm_publication_details,
        name='confirm-publication-details'),
    url(r'^author/add/$', views.manage_author, name='add-author'),
    url(r'^author/(?P<pk>[0-9]+)/$', views.author_detail, name='author-details'),
    url(r'^author/(?P<pk>[0-9]+)/edit/$', views.manage_author, name='edit-author'),
]

publications/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import gettext_lazy as _
from django.core.urlresolvers import reverse
from publications.fields import PagesField


@python_2_unicode_compatible
class Author(models.Model):
    name = models.CharField(max_length=90, editable=False)
    first_name = models.CharField(_('First Name'), max_length=30)
    middle_name = models.CharField(_('Middle Name'), max_length=30, blank=True)
    last_name = models.CharField(_('Last Name'), max_length=30)
    institution = models.CharField(_('Institution'), max_length=128, blank=True)
    email = models.EmailField(_('Email'), blank=True)

    def __str__(self):
        if not self.middle_name:
            return u'{} {}'.format(self.first_name, self.last_name)
        return u'{} {}. {}'.format(self.first_name, self.middle_name[0].upper(), self.last_name)

    def get_absolute_url(self):
        return reverse('publications:edit-author', kwargs={'pk': self.id})

    def save(self, *args, **kwargs):
        if self.id is None and self.name:
            names = [name for name in self.name.split(' ')]
            if len(names) > 2:
                self.first_name = names[0]
                self.middle_name = names[1]
                self.last_name = names[2]
            elif 1 < len(names) < 3:
                self.first_name = names[0]
                self.last_name = names[1]
        elif self.id is None and not self.name:
            if not self.middle_name:
                self.name = '{} {}'.format(self.first_name, self.last_name)
            else:
                self.name = '{} {} {}'.format(self.first_name, self.middle_name, self.last_name)
        super(Author, self).save(*args, **kwargs)


@python_2_unicode_compatible
class Publication(models.Model):
    class Meta:
        ordering = ['-year', '-id']
        verbose_name_plural = 'Publications'

    title = models.CharField(_('Title'), max_length=128, unique=True)
    authors = models.ManyToManyField(Author, through='PublicationAuthor', editable=False)
    keywords = models.CharField(_('Research Area'), max_length=128)
    year = models.PositiveIntegerField(_('Year'))
    journal = models.CharField(_('Journal'), max_length=128, blank=True)
    volume = models.IntegerField(_('Volume'), blank=True, null=True)
    number = models.IntegerField(blank=True, null=True, verbose_name=_('Issue'))
    pages = PagesField(max_length=32, blank=True)
    doi = models.CharField(max_length=128, verbose_name=_('DOI'), blank=True)
    confirmed = models.BooleanField(default=False, editable=False)
    created = models.DateTimeField(_('Date Added'), auto_now_add=True)
    updated = models.DateTimeField(_('Last Updated'), auto_now=True)

    def __init__(self, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)

        # post-process keywords
        self.keywords = self.keywords.replace(';', ',')
        self.keywords = self.keywords.replace(', and ', ', ')
        self.keywords = self.keywords.replace(',and ', ', ')
        self.keywords = self.keywords.replace(' and ', ', ')
        self.keywords = [s.strip().lower() for s in self.keywords.split(',')]
        self.keywords = ', '.join(self.keywords).lower()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('publications:edit-publication', kwargs={'pk': self.id})

    def _get_publication_url(self):
        """Returns the publication's URL by building it from doi field."""
        if self.doi:
            return 'https://doi.org/{}'.format(self.doi)
        else:
            return None
    url = property(_get_publication_url)

    def _get_keywords(self):
        if self.keywords:
            return [keyword.strip().lower() for keyword in self.keywords.split(',')]
        return None
    research_area = property(_get_keywords)


class PublicationAuthor(models.Model):
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, models.CASCADE)
    first_author = models.BooleanField(_('First Author?'), default=False)
    corresponding_author = models.BooleanField(_('Corresponding Author?'), default=False)

publications/forms.py
from dal import autocomplete
from djangoformsetjs.utils import formset_media_js
from django.forms import inlineformset_factory, ModelForm
from publications.models import Author, Publication, PublicationAuthor


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = '__all__'


class PublicationAuthorForm(ModelForm):
    class Meta:
        model = PublicationAuthor
        fields = '__all__'
        widgets = {
            'author': autocomplete.ModelSelect2(
                url='publications:author-autocomplete'
            )
        }


class PublicationForm(ModelForm):
    class Meta:
        model = Publication
        fields = '__all__'


PublicationAuthorFormset = inlineformset_factory(
    Publication,
    PublicationAuthor,
    form=PublicationAuthorForm
)

publications/views.py
import json
from dal import autocomplete
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.shortcuts import get_object_or_404, redirect, render
from .models import Author, Publication
from .forms import AuthorForm, PublicationForm, PublicationAuthorFormset


class AuthorAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Author.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


@login_required
def publication_listing(request):
    publication_list = Publication.objects.all().order_by('-year', '-id')
    paginator = Paginator(publication_list, 10)

    page = request.GET.get('page')
    try:
        publications = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        publications = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        publications = paginator.page(paginator.num_pages)
    return render(request, 'publications/publication_listing.html', {'publications': publications})


@login_required
def manage_publication(request, pk=None):
    if pk:
        publication = get_object_or_404(Publication, pk=pk)
        action = reverse('publications:edit-publication', kwargs={'pk': pk})
    else:
        publication = Publication()
        action = reverse('publications:add-publication')
    form = PublicationForm(request.POST or None, instance=publication)
    formset = PublicationAuthorFormset(request.POST or None, request.FILES or None, instance=publication)
    if form.is_valid() and formset.is_valid():
        publication = form.save()
        publication_authors = formset.save(commit=False)
        for instance in publication_authors:
            instance.publication = publication
            instance.save()
        return redirect(reverse('publications:publication-details', kwargs={'pk': publication.pk}))
    return render(
        request,
        'publications/publication_form.html',
        {
            'form': form,
            'formset': formset,
            'action': action
        }
    )


@login_required
def publication_details(request, pk):
    publication = get_object_or_404(Publication, pk=pk)
    return render(request, 'publications/publication_details.html', {'publication': publication})


@login_required
def confirm_publication_details(request):
    if request.method == 'POST' and request.is_ajax():
        try:
            publication = Publication.objects.get(id=request.POST['publication_id'])
        except (KeyError, Publication.DoesNotExist):
            pass
        else:
            Publication.objects.filter(id=publication.id).update(confirmed=True)
            response = json.dumps({"message": "You have successfully confirmed publication details"})
            return HttpResponse(response, content_type='application/json')


@login_required
def manage_author(request, pk=None):
    if pk:
        author = get_object_or_404(Author, pk=pk)
        action = reverse('edit-author', kwargs={'pk': pk})
    else:
        author = Author()
        action = reverse('add-author')
    form = AuthorForm(request.POST or None, instance=author)
    if form.is_valid():
        author = form.save()
        return redirect('detail-author', {'pk': author.pk})
    return render(request, 'publications/author_form.html', {'form': form})


@login_required
def author_detail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    return render(request, 'publications/author_detail.html', {'author': author})

publications/templates/publications/author_detail.html
{% extends 'publications/base.html' %}

publications/templates/publications/author_form.html
{% extends 'publications/base.html' %}

publications/templates/publications/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>NIMR | {% block title %}Dashboard{% endblock %}</title>

    {% block css %}
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
        <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" />
        <link href="{% static 'inspinia/css/animate.css' %}" rel="stylesheet" />
        <link href="{% static 'inspinia/css/style.css' %}" rel="stylesheet" />
    {% endblock %}

</head>

<body class="">

<div id="wrapper">

    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" src="{% static 'publications/img/nimr-logo.png' %}" />
                             </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">{{ user.username }}</strong>
                             </span> <span class="text-muted text-xs block">Administrator <b class="caret"></b></span> </span> </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li><a href="">Profile</a></li>
                        </ul>
                    </div>
                    <div class="logo-element">
                        NIMR
                    </div>
                </li>
                <li>
                    <a href="{% url 'publications:publication-listing' %}">
                        <i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span> <span class="fa arrow"></span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'publications:publication-listing' %}"><i class="fa fa-files-o"></i> <span class="nav-label">Publications</span></a>
                </li>
            </ul>

        </div>
    </nav>

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    <form class="navbar-form-custom" action="">
                        <div class="form-group">
                            <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                        </div>
                    </form>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <span class="m-r-sm text-muted welcome-message">NIMR Publications Management</span>
                    </li>


                    <li>
                        <a href="{% url 'logout' %}">
                            <i class="fa fa-sign-out"></i> Log out
                        </a>
                    </li>
                </ul>

            </nav>
        </div>
        <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-sm-4">
                <h2>This is main title</h2>
                <ol class="breadcrumb">
                    <li>
                        <a href="{% url 'publications:publication-listing' %}">This is</a>
                    </li>
                    <li class="active">
                        <strong>Breadcrumb</strong>
                    </li>
                </ol>
            </div>
            <div class="col-sm-8">
                {% block page-actions %}
                    <div class="title-action">
                        <a href="" class="btn btn-primary">This is action area</a>
                    </div>
                {% endblock %}
            </div>
        </div>

        <div class="wrapper wrapper-content animated fadeInRight">
            {% block content %}

            {% endblock %}
        </div>
        <div class="footer">
            {% block footer %}
                <div class="pull-right">
                    10GB of <strong>250GB</strong> Free.
                </div>
                <div>
                    <strong>Copyright</strong> Example Company &copy; 2016
                </div>
            {% endblock %}
        </div>

    </div>
</div>

{% block js %}
    <script src="{% static 'jquery/js/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jquery/js/plugins/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'jquery/js/plugins/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'inspinia/js/inspinia.js' %}"></script>
    <script src="{% static 'jquery/js/plugins/pace.min.js' %}"></script>
{% endblock %}

{% block extrajs %}
{% endblock %}
</body>

</html>

publications/templates/publications/err_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>NIMR | {% block title %}Dashboard{% endblock %}</title>

    {% block css %}
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'inspinia/css/animate.css' %}" rel="stylesheet">
        <link href="{% static 'inspinia/css/style.css' %}" rel="stylesheet">
    {% endblock %}

</head>

<body class="gray-bg">

<div class="middle-box text-center animated fadeInDown">
    <h1>
        {% block err-code %}

        {% endblock %}
    </h1>
    <h3 class="font-bold">
        {% block err-message %}

        {% endblock %}
    </h3>
    <div class="error-desc">
        {% block errd-esc %}

        {% endblock %}
    </div>
</div>

{% block js %}
    <script src="{% static 'jquery/js/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}
</body>

</html>

publications/templates/publications/login.html
{% load staticfiles widget_tweaks mtafiti %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>NIMR | Login</title>
    {% block css %}
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">

        <link href="{% static 'inspinia/css/animate.css' %}" rel="stylesheet">
        <link href="{% static 'inspinia/css/style.css' %}" rel="stylesheet">
    {% endblock %}
</head>

<body class="gray-bg">

<div class="loginColumns animated fadeInDown">
    <div class="row">

        <div class="col-md-6">
            <h2 class="font-bold">Welcome to NIMR staff publication system</h2>

            <p>
                The database aims to facilitate tracking of published materials, enhance communication between staff, students and interns,
                ease access of NIMR researchers work to internal staff and to other stakeholders.
            </p>

            <p>
                The database will also promote researchers into the larger medical research community.
            </p>

        </div>
        <div class="col-md-6">
            <div class="ibox-content">
                <form class="m-t" role="form" action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {% render_field form.username class+='form-control' placeholder+='Username' %}
                    </div>
                    <div class="form-group">
                        {% render_field form.password class+='form-control' placeholder+='Password' %}
                    </div>
                    <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                    <a class="btn btn-sm btn-white btn-block" href="">Login with NIMR staff mail account</a>
                </form>
            </div>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-6">
            National Institute of Medical Research
        </div>
        <div class="col-md-6 text-right">
            <small>© 2016</small>
        </div>
    </div>
</div>

</body>

</html>

publications/templates/publications/publication_details.html
{% extends 'publications/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="row">
        <div class="col-lg-offset-1 col-lg-10">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>
                        Publication Details
                    </h5>
                <span class="label {% if not publication.confirmed %}label-warning{% else %}label-success{% endif %}" id="publication-status">
                    <i class="fa {% if not publication.confirmed %}fa-exclamation{% else %}fa-check{% endif %}"></i>
                </span>
                    <div class="ibox-tools">
                        {% if not publication.confirmed %}
                            <a class="btn btn-white btn-xs" id="confirm-publication" data-publication-id="{{ publication.pk }}">
                                <i class="fa fa-thumbs-o-up"></i> Confirm
                            </a>
                            <a href="{% url 'publications:edit-publication' publication.pk %}" class="btn btn-white btn-xs" id="edit-publication">
                                <i class="fa fa-edit"></i> Edit
                            </a>
                        {% endif %}
                        {% if publication.doi %}
                            <a href="http://dx.doi.org/{{ publication.doi }}" target="_blank" class="btn btn-white btn-xs">
                                <i class="fa fa-external-link"></i> View
                            </a>
                        {% endif %}
                    </div>
                </div>
                <div class="ibox-content">
                    <dl class="dl-horizontal">
                        <dt>Title:</dt> <dd><strong>{{ publication.title }}</strong></dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Authors:</dt> <dd>{{ publication.authors.all|join:", " }}</dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Journal:</dt> <dd><strong>{{ publication.journal }}</strong></dd>
                    </dl>
                    <div class="row">
                        <div class="col-lg-2">
                            <dl class="dl-horizontal">
                                <dt>Year:</dt> <dd>{{ publication.year }}</dd>
                            </dl>
                        </div>
                        <div class="col-lg-2">
                            <dl class="dl-horizontal">
                                <dt>Volume:</dt> <dd>{{ publication.volume }}</dd>
                            </dl>
                        </div>
                        <div class="col-lg-2">
                            <dl class="dl-horizontal">
                                <dt>Issue:</dt> <dd>{{ publication.number }}</dd>
                            </dl>
                        </div>
                        <div class="col-lg-2">
                            <dl class="dl-horizontal">
                                <dt>Pages:</dt> <dd>{{ publication.pages }}</dd>
                            </dl>
                        </div>
                    </div>
                    <dl class="dl-horizontal">
                        <dt>Research Area:</dt>
                        <dd>
                            <ul class="tag-list" style="padding: 0">
                                {% for keyword in publication.research_area %}
                                    <li class="tag-item"><a href=""><i class="fa fa-tag"></i> <strong>{{ keyword }}</strong></a></li>
                                {% endfor %}
                            </ul>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script>
        $(document).ready(function () {

            $('#confirm-publication').on('click', function (event) {
                event.preventDefault();
                var publication_id = $(this).attr("data-publication-id");
                $.ajax({
                    url: "{% url 'publications:confirm-publication-details' %}",
                    type: "POST",
                    data: {
                        "publication_id": publication_id
                    },
                    success: function (response) {
                        var status = $('#publication-status');
                        $('#confirm-publication').remove();
                        $('#edit-publication').remove();
                        status.removeClass('label-warning').addClass('label-success');
                        status.find('i').removeClass('fa-exclamation').addClass('fa-check');
                        alert(response.message);
                    },
                    error: function (xhr, message , status) {
                        alert("Something didn't go well! " + status);
                    }
                });
            });

            // CSRF
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            var csrftoken = getCookie('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
    </script>
{% endblock %}

publications/templates/publications/publication_listing.html
{% extends 'publications/base.html' %}
{% load staticfiles widget_tweaks mtafiti %}

{% block page-actions %}
    <div class="title-action">
        <div class="btn-group">
            <a href="{% url 'publications:add-publication' %}" class="btn btn-white">Add Publication</a>
            <button class="btn btn-white"><span class="fa fa-plus"></span></button>
        </div>
    </div>
{% endblock %}

{% block content %}
    {% if publications %}
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="project-list">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Journal</th>
                                    <th>Year</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for publication in publications %}
                                    <tr>
                                        <td class="project-title">
                                            <a href="{% url 'publications:publication-details' publication.pk %}">{{ publication.title }}</a>
                                        </td>
                                        <td class="project-completion">
                                            {{ publication.journal }}
                                            <br />
                                            <small>Vol.:{{ publication.volume }}, Issue.:{{ publication.number }}</small>
                                        </td>
                                        <td>{{ publication.year }}</td>
                                        <td class="project-actions">
                                            <a href="https://dx.doi.org/{{ publication.doi }}" target="_blank" class="btn btn-white btn-sm">
                                                View Article <i class="fa fa-external-link"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="5">
                                        <ul class="pagination pull-right">
                                            {% if publications.has_previous %}
                                                <li>
                                                    <a href="?page={{ publications.previous_page_number }}" aria-label="Previous">
                                                        <span aria-hidden="true">&laquo;</span>
                                                    </a>
                                                </li>
                                            {% endif %}

                                            <li>
                                                <span class="active">Page {{ publications.number }} of {{ publications.paginator.num_pages }}</span>
                                            </li>

                                            {% if publications.has_next %}
                                                <li>
                                                    <a href="?page={{ publications.next_page_number }}" aria-label="Next">
                                                        <span aria-hidden="true">&raquo;</span>
                                                    </a>
                                                </li>
                                            {% endif %}
                                        </ul>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
        <div class="middle-box text-center">
            <h3 class="font-bold">You have no publication!</h3>
            <div class="text-info">
                It seems that of all the publication in the system you haven't authored any.
                You can add publications that you have authored by clicking the below button.
                <br /><a href="{% url 'publications:add-publication' %}" class="btn btn-primary m-t">Add Publication</a>
            </div>
        </div>
    {% endif %}
{% endblock %}